version: '3.3'
services:
  redis-server:
    image: 'redis'
    ports:
     - '6379:6379'
    restart: always
    volumes:
     - ./docker-config/redis_volumes:/var/lib/redis
    volumes:
     - ./docker-config/redis.conf:/var/lib/redis.conf
  mariadb:
    build:
      context: .
      dockerfile: ./docker-config/mariadb/mariadb.Dockerfile
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=codespace
     - TZ=Asia/Seoul
    volumes:
     - ./docker-config/mariadb/db_volumes:/var/lib/mysql
    ports:
     - '3306:3306'
  backend:
    image: lak9348/codespace:latest
    ports:
      - '9191:9191'
    restart: always