apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment 
  labels:
    app: nginx
spec:
  selector:
          matchLabels:
                  app: nginx
  replicas: 3
  template:
          metadata:
                  labels:
                          app: nginx
          spec:
                  tolerations:
                          - key: "virtual-kubelet.io/provider"
                            operator: "Equal"
                            value: "openstack"
                            effect: "NoSchedule"
                  containers:
                          - name: nginx
                            image: nginx:1.7.9
                            ports:
                                    - containerPort: 80
