apiVersion: v1
kind: Pod
metadata:
        name: nginx3
spec:
        tolerations:
                - key: "virtual-kubelet.io/provider"
                  operator: "Equal"
                  value: "openstack"
                  effect: "NoSchedule"
        containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                          - containerPort: 80
