server:
    port : 9191
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/codespace
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: codesoace
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret: codeholiccodeholiccodeholiccodeholiccodeholiccodeholiccodeholic
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
openstackDomain: localhost
countPerPage: 5