heat_template_version: 2013-05-23

parameters:
  public_net:
    type: string
    description: public network name
    default: admin_floating_net 
  private_net_name:
    type: string
    description: private network name
    default: net04 

resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: 172.16.200.0/24
      gateway_ip: 172.16.200.1 
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
          network: { get_param: public_net }
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }
outputs:
  private_net_id:
    description: Created private network id 
    value: { get_resource: private_net }
  private_subnet_id:
    description: Created private subnet id 
    value: { get_resource: private_subnet }
